### ISSUE TITLE
第三列最短高度bug

### ISSUE THREAD

**Issue by posebear1990** [IFE-Dollar/Personal-knowledge-management-tool#1]
但笔记内容十分少的时候会因为高度太短而露出背景，看截图
![default](https://cloud.githubusercontent.com/assets/2797600/8867474/52b50d80-31fc-11e5-9111-ec9032c3c681.PNG)

**Comment by ryuzheng** [comment]
sorry，昨天很忙，没及时处理，已经修改了，将"post-content"的背景颜色去掉，替换为设置“note-content”整个的背景颜色为白色，然后“note-title”的背景颜色为红色覆盖白色的背景，不影响笔记内容的白色背景
