### ISSUE TITLE
按钮有速度瓶颈，需要优化

### ISSUE THREAD

**Issue by posebear1990** [IFE-Dollar/Personal-knowledge-management-tool#2]

**Comment by ryuzheng** [comment]
这个按钮的速度瓶颈什么意思，没看懂，意思是不要用按钮转为其他的方式？

**Comment by posebear1990** [comment]
就是图标的网站又挂了……

**Comment by ryuzheng** [comment]
哦哦，我发现了，然后还是把字体放回我们的本地文件夹里，font文件夹里，很奇怪的是，用的明明是css3的@font，但是写到单独的css引用就出问题，我把它的css放进index.html就没问题，我已经放在index.html里面了，在你的js源码前面，在master那个branch里更新了。我再看看要不要换其他方式，但是font是很常见的方式啊。
